version: 2.1

orbs:
  gcp-gcr: circleci/gcp-gcr@0.13.0

jobs:
  build_and_push:
    executor: gcp-gcr/default
    steps:
      # test orb commands
      - checkout
      - gcp-gcr/gcr-auth
      - run:
          name: Go to app directory
          command: |
            cd app
            echo 'export TAG=${CIRCLE_SHA1:0:7}.${CIRCLE_BUILD_NUM}' >> $BASH_ENV
            docker build -t us.gcr.io/client-dev-ca/sample-image:$TAG .
      - gcp-gcr/push-image:
          google-project-id: GOOGLE_PROJECT_ID
          registry-url: us.gcr.io
          image: sample-image
          tag: ${CIRCLE_SHA1:0:7}.${CIRCLE_BUILD_NUM}

      - gcp-gcr/tag-image:
          google-project-id: GOOGLE_PROJECT_ID
          registry-url: us.gcr.io
          image: sample-image
          source-tag: ${CIRCLE_SHA1:0:7}.${CIRCLE_BUILD_NUM}
          target-tag: tagged.${CIRCLE_BUILD_NUM}
workflows:
  version: 2
  deploy_infrastructure:
    jobs:
      - build_and_push:
          filters:  # using regex filters requires the entire branch to match
            branches:
              only:  # only branches matching the below regex filters will run
                - staging
      # - deploy:
      #     requires:
      #       - build_and_push
