version: 2.1

orbs:
  gcp-gcr: circleci/gcp-gcr@0.13.0

jobs:
  build_and_push:
    executor: gcp-gcr/default
    steps:
      # test orb commands
      - checkout
      - gcp-gcr/gcr-auth:
          gcloud-service-key: GOOGLE_CREDENTIALS
      - run:
          name: Go to app directory
          command: |
            cd app
            docker build -t gcr.io/client-dev-ca/sample-image:${CIRCLE_SHA1:0:7}.${CIRCLE_BUILD_NUM} .
      - gcp-gcr/push-image:
          image: sample-image
          tag: ${CIRCLE_SHA1:0:7}.${CIRCLE_BUILD_NUM}

      - gcp-gcr/tag-image:
          image: sample-image
          source-tag: ${CIRCLE_SHA1:0:7}.${CIRCLE_BUILD_NUM}
          target-tag: v1.0
  deploy:
    docker:
      - image: hashicorp/terraform:0.13.5
    # https://circleci.com/docs/2.0/env-vars/#alpine-linux
    shell: /bin/sh -leo pipefail
    environment:
      - BASH_ENV: /etc/profile
    steps:
      #- *determine_environment
      - checkout
      - run:
          name: Setup Terraform credentials
          command: |
            echo "credentials \"app.terraform.io\" {
              token = \"${TERRAFORM_TOKEN}\"
            }" > ~/.terraformrc
      - run:
          name: Terraform initialise
          command: |
            cd platform/env-staging
            terraform init -input=false -no-color
      - run:
          name: Terraform plan
          command: |
            cd platform/env-staging
            terraform plan -input=false -no-color -out=plan/plan-${CIRCLE_BUILD_NUM}.zip
      - run:
          name: Terraform apply
          command: |
            cd platform/env-staging
            terraform apply -input=false -no-color -auto-approve plan/plan-${CIRCLE_BUILD_NUM}.zip
workflows:
  version: 2
  deploy_infrastructure:
    jobs:
      - build_and_push:
          filters:  # using regex filters requires the entire branch to match
            branches:
              only:  # only branches matching the below regex filters will run
                - staging
      - deploy:
          requires:
            - build_and_push
          filters:  # using regex filters requires the entire branch to match
            branches:
              only:  # only branches matching the below regex filters will run
                - staging
